version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Build Project
          command: xcodebuild -project PokeStudy.xcodeproj -scheme PokeStudy -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' CODE_SIGNING_ALLOWED=NO clean build -skipPackagePluginValidation -skipMacroValidation -allowProvisioningUpdates

  test:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: xcodebuild test -scheme PokeStudyTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' -enableCodeCoverage YES -skipPackagePluginValidation -skipMacroValidation -allowProvisioningUpdates
      - store_test_results:
          path: ~/Library/Developer/Xcode/DerivedData/PokeStudy/Logs/Test
      - store_artifacts:
          path: ~/Library/Developer/Xcode/DerivedData/PokeStudy/Logs/Test
          destination: test-output
      - codecov/upload: { validate: false }

workflows:
  build_and_test_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
